### ISSUE TITLE
New plot files seem to be missing?

### ISSUE THREAD

**Issue by drphilmarshall** [tommasotreu/HIGHRESOLUTIONIMAGING#28]

**Comment by drphilmarshall** [comment]
Here's the details:

grep Error High_resolution_imaging_requirements.log

>
! Package pdftex.def Error: File `figures/gamma_0330_anti_4QSOimages_HST.png' not found
! Package pdftex.def Error: File `figures/gamma_0330_anti_4QSOimages_JWST.png' not found
! Package pdftex.def Error: File `figures/gamma_0330_anti_4QSOimages_Keck.png' not found
! Package pdftex.def Error: File `figures/gamma_0330_anti_4QSOimages_NGAO.png' not found
! Package pdftex.def Error: File `figures/gamma_0330_anti_4QSOimages_EWL.png' not found
! Package pdftex.def Error: File `figures/gamma_0330_2QSOimages_HST.png' not found
! Package pdftex.def Error: File `figures/gamma_0330_2QSOimages_JWST.png' not found
! Package pdftex.def Error: File `figures/gamma_0330_2QSOimages_Keck.png' not found
! Package pdftex.def Error: File `figures/gamma_0330_2QSOimages_NGAO.png' not found
! Package pdftex.def Error: File `figures/gamma_0330_2QSOimages_E_W_L.png' not found

**Comment by XiaoleiMeng** [comment]
Hi, Phil,

I am afraid you edit in a old version. In our recent version, we changed the figures and gave them new names.

Best,

Xiao-Lei

**Comment by XiaoleiMeng** [comment]
Hi, Phil, sorry, I think we use different versions...I am thinking about how to solve this problem.

**Comment by drphilmarshall** [comment]
This problem was fixed in #29, once I had reverted to Tommaso's final version of the tex.
