### ISSUE TITLE
Link in arXiv comment gives 404

### ISSUE THREAD

**Issue by andycasey** [tommasotreu/HIGHRESOLUTIONIMAGING#31]
The comment in astro-ph says:

    A full resolution, continuously updated version can be viewed at
    https://github.com/tommasotreu/HIGHRESOLUTIONIMAGING/blob/master/paper/High_resolution_imaging_requirements.pdf
    We invite comments and questions at https://github.com/tommasotreu/HIGHRESOLUTIONIMAGING/issues

But the `High_resolution_imaging_requirements.pdf` link gives a 404 because only the TeX exists in the repository, and not the PDF.

**Comment by drphilmarshall** [comment]
Thanks @andycasey! Paper is now there.

**Comment by andycasey** [comment]
:+1:
