### ISSUE TITLE
Kochanek et al. 2001 

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#36]
(3)I should note that Kochanek et al. (2001) is among the first who emphasized the importance of lensed host galaxies for time delay cos- mography and demonstrated how it breaks the degeneracy in lens mass models.
----------------------------------------

Kochanek et al. (2001) (http://iopscience.iop.org/0004-637X/547/1/50/pdf/52095.web.pdf) emphasized that Einstein ring images of the host galaxies can be used to constrain the mass distributions of lens galaxies and the Hubble constant. In this paper, they demonstrated how these constrains break the lens model degeneracies to determine the mass distributions of lens and the Hubble constant from time-delay measurements.

**Comment by tommasotreu** [comment]
Add references to the Kochanek et al. paper
