### ISSUE TITLE
how the PSF uncertainty would propagate into \gamma'

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#37]
(4)Throughout the paper the authors ignore the PSF uncertainty and assume the perfect knowledge about the PSF. While I understand the authors’ point that by doing so the results represent a lower limit of the total uncertainty, I’d like to see a more extensive discussion on how the PSF uncertainty would propagate into γ′, given the critical importance of accurate PSF characterizations for AO observations. In Introduction the authors mention Marshall et al. and Lagattuta et al., but these papers are not very relevant in this context as systems studied in those papers are more like galaxy-galaxy strong lensing. In the case of quasar lensing, there must be a degeneracy between the PSF wing (from quasar images) and surface brightness profile of a lensed host galaxy, which has to be carefully addressed. Agnello et al. mentioned in the paper did not fully take account of the PSF uncertainty. In a recent paper by Rusu et al. (2015) adopted a parametrized PSF model and marginalized over PSF parameters when deriving physical parameters, and thus should be helpful in discussing potential impacts of PSF uncertainties and possible future extensions of the present paper to address the propagation of PSF uncertainties to the final result.
----------------------------------------------------

Because of the rapid change of the atmospheric turbulence which induce different responses from the AO system, the observed PSF needs be calibrated. A separate Gaussian or Moffat profile cannot describe a AO PSF very well. In general the shape of a AO PSF is described as two components: a nearly diffraction-limited core of FWHM which is typically approximated by a Gaussian, and the seeing limited halo/wing of FWHM which is approximated by a Moffat profile. This is caused by the characteristic that the Moffat profile facilitate to describe the more extended wing than a Gaussian. For quasar lensing, there must be a degeneracy between the PSF wing (from the quasar image) and the surface brightness profile of a lensed host galaxy. For constructing a well-characterized PSF for each system, Rusu et al. 2015 used a new technique by adopting an analytical PSF model or a hybrid PSF model and simultaneously optimizing for the global PSF parameters as well as the lens system parameters. In the analysis PSF profiles, they found that the 2 Moffat profile provides the best fit. In the hybrid PSF approach, they use the observed brightness distribution of the bright image only in its central regions, and replacing the wings after a certain cut radius with analysis wings from the 2 Moffat fit. By comparing with the simulations for each system using observed PSF star, it can account for the systematics. 

But I cannot understand the referee's purpose very well. I do not know how to describe the propagation of PSF uncertainties to the final result. Or do we need perform simulations to answer this question? If that's the case, it is a big project.

**Comment by tommasotreu** [comment]
I will respond to this. I don't think we need to do more simulations

**Comment by tommasotreu** [comment]
I added a paragraph at the end of the paper. We might want to revisit it after XLM has finished simulations with Moffat profiles.
