### ISSUE TITLE
give a quantitative description of the SQLS sample

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#38]
(5)In Sec. 3.1: “... of currently known lenses, selected from the Sloan Digital Sky Survey,” The current largest quasar lens sample comes from the SDSS Quasar Lens Search, containing more than 50 quasar lenses. It would be informative to give a quantitative description of the SQLS sample (typical magnitudes, quad/double ratio, etc), citing references.
---------------------------------------------------------

Actually, in addition to strongly lensed galaxies, strongly lensed quasars are also searched for. The current largest quasar lens sample comes from the SDSS Quasar Lens Search (SQLS; Oguri et al. 2006; Inada et al. 2012). The well-defined statistical quasar lens sample of it consists 26 lensed quasars which is selected from SDSS Data Release 7 (DR7) quasar catalog with Galactic extinction-corrected i-band magnitudes $15.0 \leq i \leq19.1$ in the low redshift ($0.6 < z < 2.2$), adopting morphological (image separations of $1'' < \theta < 20''$) and color ($i$-band magnitude difference between two images should be smaller than 1.25 mag) selection algorithms. Among the 26 lensed quasars, the number of the quad and double images are 4 and 21 respectively, the remaining is a 5-image cluster lens. Meanwhile, 36 additional lensed quasars are identified from the DR7 quasar catalog, which contains 4 quad-image systems, 30 double-image systems, the rest two are 5-image and 3-image cluster systems. Many of them were discovered with the outside magnitude, redshift, and image separation selection algorithms to quasars compare with the statistical lens sample. Due to the lacking of some crucial parameter values of host and lens galaxies, we do not use SQLS to perform our mock simulations.

**Comment by tommasotreu** [comment]
Hi Xiao-Lei, this is good, please ad this response to the paper and refer to the extra information in the response to the referee. When done I will go trhough it for polishing
