### ISSUE TITLE
“As in the real-system used as inspiration” This sounds a bit odd.

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#39]
(6)Also in Sec. 3.1: “As in the real-system used as inspiration” This sounds a bit odd, because SLACS and SL2S (which that sentence is referring) are not quasar lens surveys but galaxy-galaxy strong lens surveys. For example typical redshifts can be quite different.
------------------------------------------------------------

I think there's no problem with this description. What do you think about it?

**Comment by tommasotreu** [comment]
Tommaso will explain

**Comment by tommasotreu** [comment]
edited the text accordingly
