### ISSUE TITLE
parameters in table2 and 3

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#40]
(7)Sec 3.2: “... are listed in Table 2 and Table 3.” In fact light and lens models are described later in Sec. 4, so at this point readers have no idea what these parameters mean.
----------------------------------------------------------------

The structural parameters of the four systems are listed in Table 2 and Table 3, including the position of the source with respect to the lens, the effective radius, the axis radio of the surface brightness distribution, the position angle, the S{\'e}rsic index, and the magnitude in I, K, VIS, and H band for the surface brightness profile model; the redshift, the Einstein radius, the ratio of the mass distribution, the position angle, and the power-law slope of the mass for the lens model.

**Comment by tommasotreu** [comment]
Xiao-Lei, I would say you just have to explain what the parameters mean, or move the reference to the table to later on. The former is probably easiest.
