### ISSUE TITLE
a quasar 1 mag brighter than the host

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#41]
(8)The authors choose a quasar 1 mag brighter than the host galaxy in their simulations. It would be useful to check previous analysis of lensed quasar hosts to see how typical this assumption is compared with observed lensed quasar systems. For example Peng et al. (2006) analyzed a large sample of quasar lenses using HST. Rusu et al. (2015) mentioned above also added several more quasar lens systems with host detections.
-----------------------------------------------------------

In previous work (Peng et al. 2006; Peng et al. 2006; Rusu et al. 2015), though in some special cases the AGNs are fainter than their host galaxies, the AGNs are 0 to 3 magnitudes brighter than the host in the bands we choose. So the adopted magnitudes are typical and listed in Table 4.

**Comment by tommasotreu** [comment]
Please add this to the response to the referee
