### ISSUE TITLE
the images with the lensing galaxy

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#43]
(10)It looks like lensing galaxies are not shown in Figs. 3-6, I guess this is just to better show quasar images and host galaxies. If so this point should be clearly mentioned in the paper. In practice a lensing galaxy is fitted simultaneously (if I understand correctly), so it may be helpful to show simulated images with lensing galaxies as well.
-----------------------------------------------------------

Yes, the purpose that the lens galaxies are not shown is to better show the quasar and host images. 

Hi, guys, do you want to add the lens galaxy in the figures or we mention our purpose in the paper?

**Comment by tommasotreu** [comment]
Please clarify in the text and show and leave as is, we can tell the referee that we do not want to double the already large number of figures!!
