### ISSUE TITLE
the sky level in fitting

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#44]
(11)In the non-linear fitting described in Sec. 4.2, is the sky level not included as a fitting parameter? Or the sky level is fixed to the true value during fitting?
-----------------------------------------------------------

In fitting process in our work, the non-linear parameters contain the necessary parameters for source and deflector brightness model, the deflector mass model, and point source's position in the image plane. The sky level is fixed to the true value in this process.

**Comment by tommasotreu** [comment]
Please add this to the reponse and close the issue
