### ISSUE TITLE
2% accuracy

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#45]
(12)In Sec. 4.3 and 5 there are sentences like “determine γ′ with 2% pre- cision”. This is related to my first comment, suppose that the input γ′ value is 2, “2% precision” is different from γ′ uncertainties of 0.02. If one wants to determine H0 with 2% accuracy, γ′ has to be deter- mined with an accuracy of 0.02, which corresponds to 1% precision of γ′ determination for the fiducial γ′ value of 2. Please clarify.
-----------------------------------------------------------

In our code, we use a parameter named 'eta' to describe the slope of the mass distribution. SIE is defined with eta = 1. So "2\% precision" is the same with $\gamma'$ uncertainties of 0.02.

**Comment by tommasotreu** [comment]
Adri, can you please go through the paper and homogenize all this stuff? If you can't do it let me know and I'll assign it to someone else, or maybe just do it myself.
