### ISSUE TITLE
noise realization

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#46]
(13)In Sec. 5: “we generate 30 mock systems” These mock systems refer to different noise realizations of the same input image?
----------------------------------------------------

For each exposure time with each instrument, we generate 30 mock systems for most configurations and 10 mock systems for TMT with the view of saving computing time. In each mock system, we use the standard normal distribution of the noise. So, for the 30 mock systems, they have different noise realizations with the same other input values.

**Comment by tommasotreu** [comment]
Good response. I think we can add this to the reponse to the referee and close the issue.
