### ISSUE TITLE
the insert in each panel

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#47]
(14)Figs. 7-10: I don’t quite understand the insert in each panel. If I read the caption literally, x and y axes refer to the same quantity and therefore all the points lie exactly on the y = x line? Then what information does this plot carry?
------------------------------------------------

Yes, the x and y axes in the insert refer to the same quantity and all the points lie exactly on the y=x line. We keep the insert because it contains the standard deviation information of each simulation.

**Comment by tommasotreu** [comment]
I think we can just take it out, as the standar deviation information can be read from the error bars anyway, so it's best to make the referee happy.
